### ISSUE TITLE
Is `to_opengl` a must for sampling env map?

### ISSUE THREAD

**Issue by yifanlu0227** [fudan-zvg/PVG#20]
https://github.com/fudan-zvg/PVG/blob/3ea4b176b03e901800df9e95edda00ec66b3a795/scene/envlight.py#L9

Hi! The ray direction is already in the world coordinate, and I am confused about why we need to do this conversion. Could you explain it?

Looking forward to your help and reply

**Comment by SuLvXiangXin** [comment]
Hi, I've noticed that nvdiffrast uses the y-axis upward, while we use the z-axis, just to align with nvdiffrast. I think it's also okay without this conversion.

**Comment by yifanlu0227** [comment]
Thanks!
