### ISSUE TITLE
Discrepancy in used pts_depth in comparison to traditional depth_map. 

### ISSUE THREAD

**Issue by skrya** [fudan-zvg/PVG#21]
Dear Authors, 

Thanks for the excellent work!! 

I have a question on how the pts_depth is computed. It seems to be very different from the traditional depth_map obtained from  lidar points. 

For example for the 0006 in KITTI, the depth map obtained for a frame has a approx. range of 0 to 78. However, pts_depth seem to have a range of approx. 0 to 8-9. 

Can you please clarify as it hard for me to understand the purpose of it fully.

Thanks!

**Comment by SuLvXiangXin** [comment]
Hi, I think the discrepancy in the depth range is due to a coordinate transformation, as we normalize camera poses.

**Comment by skrya** [comment]
Thank you for your response. Could you please guide me to the specific part of the code that handles camera pose orientation and centering, without applying normalization? I am particularly interested in calculating the predicted metric depth.

**Comment by skrya** [comment]
Figured it out. You can close this issue. Thank you for the suggestion.
