### ISSUE TITLE
关于原始高斯的实验设置

### ISSUE THREAD

**Issue by Korace0v0** [fudan-zvg/PVG#24]
非常棒的工作，感谢开源！

我希望尝试一下与原始高斯的对比实验，但我该修改哪些配置才能退化成原始的高斯呢？

Thanks again！

**Comment by Fumore** [comment]
你好，你可以尝试将t_init设置为无限大，并将velocity_lr, scaling_t_lr, t_lr_init置0来退化成3D Gaussian。但除此之外，还有很多细节（如config和loss）和原始Gaussian不太一样，可能还是将dataloader迁移到原始Gaussian更加方便。

**Comment by Korace0v0** [comment]
非常感谢！
