### ISSUE TITLE
About .tfrecord Format Waymo Data

### ISSUE THREAD

**Issue by Ysc-shark** [fudan-zvg/PVG#26]
Great work!

The four pre-processed Waymo scenes you provided are already processed. 
However, the original Waymo data comes in .tfrecord format. 
I would like to use the waymo_kitti_converter tool to convert the data you provided into the KITTI format. 

Could you advise on how to convert these four example datasets back to the original .tfrecord format? 
Alternatively, could you provide the original .tfrecord data?

**Comment by Ysc-shark** [comment]
Could you please tell me the original file sequence names for the four pre-processed Waymo data?

**Comment by Fumore** [comment]
![image](https://github.com/fudan-zvg/PVG/assets/52318421/45d3068b-b187-4106-b213-69224da47437)
Sorry to reply you late. The first 4 tfrecord are dynamic scenes used in paper, and the last 2 is for static waymo scenes.

**Comment by Ysc-shark** [comment]
> ![image](https://private-user-images.githubusercontent.com/52318421/341730761-45d3068b-b187-4106-b213-69224da47437.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMTkwMjEsIm5iZiI6MTcxOTMxODcyMSwicGF0aCI6Ii81MjMxODQyMS8zNDE3MzA3NjEtNDVkMzA2OGItYjE4Ny00MTA2LWIyMTMtNjkyMjRkYTQ3NDM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDEyMzIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNGY2M2JiMjYxODM0NTA0NzY3MTJkY2NhMDllNzRjNjEyYWJjYWNkMmVlMjFhYTVhYTRjY2JkMjFmNWIzZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._yf5ExvHltVdVZ0CPJgsCTfr_v4NUlsY4y8SqNX9hmc) Sorry to reply you late. The first 4 tfrecord are dynamic scenes used in paper, and the last 2 is for static waymo scenes.

thanks
