### ISSUE TITLE
Waymo evaluation sequence

### ISSUE THREAD

**Issue by sus71** [fudan-zvg/PVG#3]
Hi! Thanks for this nice work.

Which sequences did you use for results reported in Table 2. Novel view synthesis of static scenes on Waymo?

**Comment by SuLvXiangXin** [comment]
Hi, sorry for the delay reply.  We use `segment-14004546003548947884_2331_861_2351_861_with_camera_labels.tfrecord` and  `segment-16608525782988721413_100_000_120_000_with_camera_labels.tfrecord` in Table 2, same as in S-NeRF.

**Comment by sus71** [comment]
thanks!
