### ISSUE TITLE
Thank you for your excellent work! What is the minimum GPU configuration required to train the PVG algorithm? Can it be trained with a single 4090 GPU?

### ISSUE THREAD

**Issue by Tianci-Wen** [fudan-zvg/PVG#4]

**Comment by Tianci-Wen** [comment]
I see that in your paper, you used A6000 to train for an hour. I don’t know how much your GPU memory consumption is? I don’t know if I can use a 4090 GPU for training, because the original 3DGS only requires a 4090 GPU for training.

**Comment by SuLvXiangXin** [comment]
Hi, for Kitti, it costs less than 10GB; for waymo, it costs around 20GB. If you have an OutOfMemory issue, you can try to decrease `densify_until_num_points` in config.

**Comment by Tianci-Wen** [comment]
Yes, I have tested all sequences and scenarios. The 4090 can run this algorithm perfectly, and the memory consumption is consistent with what you said. Thank you very much!
